-- MODELO RELACIONAL SST/PESV PARA DRAWSQL (PostgreSQL).
-- Copia todo este archivo y pegalo en la opcion de importar SQL/DDL de DrawSQL.
-- Contiene las 18 tablas, sus claves y relaciones; no incluye datos.

CREATE TABLE countries (
  country_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);
CREATE TABLE departments (
  department_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id bigint NOT NULL REFERENCES countries(country_id),
  name text NOT NULL,
  UNIQUE (country_id, name)
);
CREATE TABLE municipalities (
  municipality_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id bigint NOT NULL REFERENCES departments(department_id),
  name text NOT NULL,
  UNIQUE (department_id, name)
);
CREATE TABLE tenant_sizes (
  tenant_size_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text NOT NULL UNIQUE
);
CREATE TABLE type_system_sst (
  system_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  description text NOT NULL
);
CREATE TABLE phva_stages (
  stage_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE CHECK (code IN ('P','H','V','A')),
  name text NOT NULL UNIQUE,
  display_order integer NOT NULL UNIQUE CHECK (display_order BETWEEN 1 AND 4)
);
CREATE TABLE tenants (
  tenant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identification text NOT NULL UNIQUE,
  name text NOT NULL,
  contact_email text NOT NULL,
  phone text,
  tenant_size_id bigint NOT NULL REFERENCES tenant_sizes(tenant_size_id),
  municipality_id bigint NOT NULL REFERENCES municipalities(municipality_id),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX tenants_municipality_idx ON tenants(municipality_id);
CREATE INDEX tenants_size_idx ON tenants(tenant_size_id);

CREATE TABLE positions (
  position_id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL REFERENCES tenants(tenant_id),
  description text NOT NULL,
  PRIMARY KEY (tenant_id, position_id),
  UNIQUE (tenant_id, description),
  CHECK (position_id > 0)
);
CREATE TABLE persons (
  person_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tenants(tenant_id),
  position_id bigint NOT NULL,
  identification text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, identification),
  UNIQUE (tenant_id, email),
  FOREIGN KEY (tenant_id, position_id) REFERENCES positions(tenant_id, position_id)
);
CREATE INDEX persons_position_idx ON persons(tenant_id, position_id);

CREATE TABLE modules (
  module_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_id bigint NOT NULL REFERENCES type_system_sst(system_id),
  title text NOT NULL,
  description text NOT NULL,
  display_order integer NOT NULL CHECK (display_order > 0),
  UNIQUE (system_id, title),
  UNIQUE (system_id, display_order)
);
CREATE TABLE formats_sst (
  format_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id bigint NOT NULL REFERENCES modules(module_id),
  title text NOT NULL,
  UNIQUE (module_id, title)
);
CREATE TABLE templates (
  template_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  format_id bigint NOT NULL REFERENCES formats_sst(format_id),
  title text NOT NULL,
  UNIQUE (format_id, title)
);
CREATE TABLE evaluations (
  evaluation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id bigint NOT NULL REFERENCES modules(module_id),
  title text NOT NULL,
  description text,
  UNIQUE (module_id, title)
);

CREATE TABLE tenantsystems (
  tenant_id bigint NOT NULL REFERENCES tenants(tenant_id),
  system_id bigint NOT NULL REFERENCES type_system_sst(system_id),
  enabled_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, system_id)
);
CREATE INDEX tenantsystems_system_idx ON tenantsystems(system_id);
CREATE TABLE tenant_modules (
  tenant_id bigint NOT NULL,
  module_id bigint NOT NULL,
  is_enabled boolean NOT NULL DEFAULT true,
  enabled_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, module_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id),
  FOREIGN KEY (module_id) REFERENCES modules(module_id)
);
CREATE INDEX tenant_modules_module_idx ON tenant_modules(module_id);

-- Cada asignacion es un documento exigible; estado define el indicador.
CREATE TABLE tenanttemplates (
  tenanttemplate_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL,
  template_id bigint NOT NULL,
  stage_id bigint NOT NULL REFERENCES phva_stages(stage_id),
  status text NOT NULL DEFAULT 'no_iniciado'
    CHECK (status IN ('no_iniciado','borrador','finalizado')),
  assigned_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by text,
  UNIQUE (tenant_id, template_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id),
  FOREIGN KEY (template_id) REFERENCES templates(template_id)
);
CREATE INDEX tenanttemplates_stage_idx ON tenanttemplates(tenant_id, stage_id);
CREATE INDEX tenanttemplates_status_idx ON tenanttemplates(tenant_id, status);

CREATE TABLE editing_locks (
  lock_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenanttemplate_id bigint NOT NULL REFERENCES tenanttemplates(tenanttemplate_id),
  person_id bigint NOT NULL REFERENCES persons(person_id),
  expires_at timestamptz NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX editing_locks_one_active_idx
  ON editing_locks(tenanttemplate_id) WHERE is_active;
CREATE INDEX editing_locks_expiry_idx ON editing_locks(expires_at) WHERE is_active;

CREATE TABLE tenant_audit (
  audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL,
  changed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  changed_by text NOT NULL DEFAULT CURRENT_USER,
  old_name text NOT NULL,
  new_name text NOT NULL,
  old_email text NOT NULL,
  new_email text NOT NULL,
  old_is_active boolean NOT NULL,
  new_is_active boolean NOT NULL
);
CREATE INDEX tenant_audit_tenant_idx ON tenant_audit(tenant_id, changed_at DESC);
